PATH_APP_LOAD_PARAMS += "44'/60'"
TICKER = "ETH"
CHAIN_ID = 3
# Allow to derive ETH 2 public keys
PATH_APP_LOAD_PARAMS += "12381/3600"
CURVE_APP_LOAD_PARAMS += bls12381g1
DEFINES += HAVE_ETH2
APPNAME = "Eth Ropsten"
DEFINES += HAVE_BOLOS_APP_STACK_CANARY
