/**
 * @file test_network.c
 * @brief Unit tests for chain-id ↔ network resolution in src/network.c.
 *
 * Every "Network: …" line shown to the user is generated by this module:
 *   - get_network_name_from_chain_id() looks up the chain in the dynamic
 *     list, falling back to the app's own name (APPNAME) for its native chain,
 *   - get_network_as_string_from_chain_id() falls back to the decimal
 *     chain_id when no name is known,
 *   - get_displayable_ticker() picks between the dynamic / chain_config /
 *     "???" sources for the ticker badge,
 *   - app_compatible_with_chain_id() decides whether the running app may
 *     sign for a given chain at all.
 *
 * The tests stub the few globals the module reads (`g_chain_config`,
 * `g_dynamic_network_list`, `txContext`, `tmpContent`) directly rather
 * than dragging in the full app, and rely on the real implementations of
 * format_u64 / u64_from_BE so the format-fallback path is exercised
 * end-to-end.
 */

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "shared_context.h"
#include "network.h"
#include "network_info.h"  // extern g_dynamic_network_list
#include "caller_app.h"
#include "wraps.h"  // extern g_tx_content

// =============================================================================
// Globals the module reads — provide storage here.
// =============================================================================

static chain_config_t s_chain_cfg = {.chain_id = 1, .ticker = "ETH", .coin_type = 60};

// =============================================================================
// Test fixtures / helpers
// =============================================================================

static int reset_globals(void **state) {
    (void) state;
    memset(&txContext, 0, sizeof(txContext));
    memset(&tmpContent, 0, sizeof(tmpContent));
    memset(&g_tx_content, 0, sizeof(g_tx_content));
    txContext.content = &g_tx_content;
    g_dynamic_network_list = NULL;
    s_chain_cfg.chain_id = 1;
    strlcpy(s_chain_cfg.ticker, "ETH", sizeof(s_chain_cfg.ticker));
    return 0;
}

// =============================================================================
// find_dynamic_network_by_chain_id
// =============================================================================

static void test_find_dynamic_empty_list_returns_null(void **state) {
    (void) state;
    assert_null(find_dynamic_network_by_chain_id(1));
}

static void test_find_dynamic_one_match(void **state) {
    (void) state;
    network_info_t n = {0};
    n.chain_id = 4242;
    strlcpy(n.name, "TestNet", sizeof(n.name));
    strlcpy(n.ticker, "TST", sizeof(n.ticker));
    g_dynamic_network_list = &n;

    network_info_t *found = find_dynamic_network_by_chain_id(4242);
    assert_ptr_equal(found, &n);
    assert_null(find_dynamic_network_by_chain_id(9999));
}

static void test_find_dynamic_walks_list_and_finds_second(void **state) {
    (void) state;
    network_info_t a = {0};
    a.chain_id = 11;
    network_info_t b = {0};
    b.chain_id = 22;
    a.node.next = (flist_node_t *) &b;
    g_dynamic_network_list = &a;

    assert_ptr_equal(find_dynamic_network_by_chain_id(11), &a);
    assert_ptr_equal(find_dynamic_network_by_chain_id(22), &b);
    assert_null(find_dynamic_network_by_chain_id(33));
}

// =============================================================================
// get_network_name_from_chain_id
// =============================================================================

static void test_get_name_known_hardcoded_returns_name(void **state) {
    (void) state;
    uint64_t cid = 1;  // Ethereum
    const char *name = get_network_name_from_chain_id(&cid);
    assert_non_null(name);
    assert_string_equal(name, "Ethereum");
}

static void test_get_name_zero_chain_id_returns_null(void **state) {
    (void) state;
    uint64_t cid = 0;
    assert_null(get_network_name_from_chain_id(&cid));
}

static void test_get_name_unknown_chain_id_returns_null(void **state) {
    (void) state;
    uint64_t cid = 0xDEADBEEF;
    assert_null(get_network_name_from_chain_id(&cid));
}

static void test_get_name_dynamic_shadows_hardcoded(void **state) {
    (void) state;
    // Inject a dynamic entry on chain_id=1 with a different name — it must
    // win over the hardcoded "Ethereum".
    network_info_t dyn = {0};
    dyn.chain_id = 1;
    strlcpy(dyn.name, "EthereumFork", sizeof(dyn.name));
    strlcpy(dyn.ticker, "FORK", sizeof(dyn.ticker));
    g_dynamic_network_list = &dyn;

    uint64_t cid = 1;
    const char *name = get_network_name_from_chain_id(&cid);
    assert_string_equal(name, "EthereumFork");
}

// =============================================================================
// get_network_as_string_from_chain_id
// =============================================================================

static void test_get_as_string_known_copies_name(void **state) {
    (void) state;
    network_info_t dyn = {0};
    dyn.chain_id = 137;  // Polygon, provided dynamically
    strlcpy(dyn.name, "Polygon", sizeof(dyn.name));
    g_dynamic_network_list = &dyn;

    char out[NETWORK_STRING_MAX_SIZE + 1];
    memset(out, 0, sizeof(out));
    assert_true(get_network_as_string_from_chain_id(out, sizeof(out), 137));
    assert_string_equal(out, "Polygon");
}

static void test_get_as_string_unknown_formats_decimal(void **state) {
    (void) state;
    char out[NETWORK_STRING_MAX_SIZE + 1];
    memset(out, 0, sizeof(out));
    assert_true(get_network_as_string_from_chain_id(out, sizeof(out), 4242));
    assert_string_equal(out, "4242");
}

static void test_get_as_string_unknown_small_buffer_fails(void **state) {
    (void) state;
    char out[2];  // not enough to hold "4242" + NUL
    assert_false(get_network_as_string_from_chain_id(out, sizeof(out), 4242));
}

// =============================================================================
// chain_is_ethereum_compatible
// =============================================================================

static void test_chain_compatible_known_true(void **state) {
    (void) state;
    network_info_t dyn = {0};
    dyn.chain_id = 137;  // known because provided dynamically
    g_dynamic_network_list = &dyn;

    uint64_t cid = 137;
    assert_true(chain_is_ethereum_compatible(&cid));
}

static void test_chain_compatible_native_true(void **state) {
    (void) state;
    // The app's own chain is always compatible, even without a dynamic network.
    uint64_t cid = 1;
    assert_true(chain_is_ethereum_compatible(&cid));
}

static void test_chain_compatible_unknown_false(void **state) {
    (void) state;
    uint64_t cid = 0xDEADBEEF;
    assert_false(chain_is_ethereum_compatible(&cid));
}

// =============================================================================
// app_compatible_with_chain_id
// =============================================================================

static void test_app_compatible_same_chain_id(void **state) {
    (void) state;
    s_chain_cfg.chain_id = 1;
    uint64_t cid = 1;
    assert_true(app_compatible_with_chain_id(&cid));
}

static void test_app_compatible_both_in_table(void **state) {
    (void) state;
    // App native chain (1) is always compatible; the target (137) is compatible
    // because it is provided as a dynamic network.
    network_info_t dyn = {0};
    dyn.chain_id = 137;
    g_dynamic_network_list = &dyn;

    uint64_t cid = 137;
    assert_true(app_compatible_with_chain_id(&cid));
}

static void test_app_compatible_target_unknown_rejected(void **state) {
    (void) state;
    s_chain_cfg.chain_id = 1;  // Ethereum
    uint64_t cid = 0xDEADBEEF;
    assert_false(app_compatible_with_chain_id(&cid));
}

// =============================================================================
// get_tx_chain_id — dispatches on txContext.txType
// =============================================================================

static void test_get_tx_chain_id_legacy_reads_v(void **state) {
    (void) state;
    txContext.txType = LEGACY;
    // chainID encoded in v (BE)
    g_tx_content.v[0] = 0x00;
    g_tx_content.v[1] = 0x89;  // 137
    g_tx_content.vLength = 2;
    assert_int_equal(get_tx_chain_id(), 137);
}

static void test_get_tx_chain_id_eip1559_reads_tmpcontent(void **state) {
    (void) state;
    txContext.txType = EIP1559;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x00;
    tmpContent.txContent.chainID.value[1] = 0x01;  // 1
    tmpContent.txContent.chainID.length = 2;
    assert_int_equal(get_tx_chain_id(), 1);
}

static void test_get_tx_chain_id_eip2930_reads_tmpcontent(void **state) {
    (void) state;
    txContext.txType = EIP2930;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x10;
    tmpContent.txContent.chainID.value[1] = 0xA5;
    tmpContent.txContent.chainID.value[2] = 0xD4;
    tmpContent.txContent.chainID.value[3] = 0xE8;
    tmpContent.txContent.chainID.length = 4;
    assert_int_equal(get_tx_chain_id(), 0x10A5D4E8);
}

static void test_get_tx_chain_id_eip7702_reads_tmpcontent(void **state) {
    (void) state;
    txContext.txType = EIP7702;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x01;
    tmpContent.txContent.chainID.length = 1;
    assert_int_equal(get_tx_chain_id(), 1);
}

static void test_get_tx_chain_id_unknown_type_returns_zero(void **state) {
    (void) state;
    txContext.txType = 0x33;  // anything not listed
    assert_int_equal(get_tx_chain_id(), 0);
}

static void test_get_network_as_string_uses_current_tx_chain_id(void **state) {
    (void) state;
    // get_network_as_string() is a thin wrapper that reads the current
    // tx_chain_id and forwards to get_network_as_string_from_chain_id.
    network_info_t dyn = {0};
    dyn.chain_id = 137;  // Polygon, provided dynamically
    strlcpy(dyn.name, "Polygon", sizeof(dyn.name));
    g_dynamic_network_list = &dyn;

    txContext.txType = EIP1559;
    memset(tmpContent.txContent.chainID.value, 0, INT256_LENGTH);
    tmpContent.txContent.chainID.value[0] = 0x00;
    tmpContent.txContent.chainID.value[1] = 0x89;  // 137
    tmpContent.txContent.chainID.length = 2;
    char out[16] = {0};
    assert_true(get_network_as_string(out, sizeof(out)));
    assert_string_equal(out, "Polygon");
}

// =============================================================================
// get_displayable_ticker
// =============================================================================

static void test_displayable_ticker_known_returns_table(void **state) {
    (void) state;
    network_info_t dyn = {0};
    dyn.chain_id = 137;  // Polygon, provided dynamically
    strlcpy(dyn.ticker, "POL", sizeof(dyn.ticker));
    g_dynamic_network_list = &dyn;

    uint64_t cid = 137;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg);
    assert_string_equal(t, "POL");
}

static void test_displayable_ticker_falls_back_to_chain_cfg(void **state) {
    (void) state;
    s_chain_cfg.chain_id = 999999;  // not in the table
    strlcpy(s_chain_cfg.ticker, "MYAPP", sizeof(s_chain_cfg.ticker));
    uint64_t cid = 999999;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg);
    assert_string_equal(t, "MYAPP");
}

static void test_displayable_ticker_unknown_returns_placeholder(void **state) {
    (void) state;
    s_chain_cfg.chain_id = 1;  // chain_cfg won't match
    uint64_t cid = 0xDEADBEEF;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg);
    assert_string_equal(t, "???");
}

static void test_displayable_ticker_dynamic_shadows(void **state) {
    (void) state;
    // A dynamic entry provides the ticker, taking precedence over the chain_config
    // fallback even for the app's native chain.
    network_info_t dyn = {0};
    dyn.chain_id = 1;
    strlcpy(dyn.ticker, "DYN", sizeof(dyn.ticker));
    g_dynamic_network_list = &dyn;

    uint64_t cid = 1;
    const char *t = get_displayable_ticker(&cid, &s_chain_cfg);
    assert_string_equal(t, "DYN");
}

// =============================================================================
// get_clone_network_name
// =============================================================================

static void test_clone_name_null_app_returns_null(void **state) {
    (void) state;
    assert_null(get_clone_network_name(NULL));
}

static void test_clone_name_non_clone_returns_null(void **state) {
    (void) state;
    caller_app_t app = {.name = "MyPlugin", .type = CALLER_TYPE_PLUGIN};
    assert_null(get_clone_network_name(&app));
}

static void test_clone_name_clone_returns_name(void **state) {
    (void) state;
    caller_app_t app = {.name = "ETHClone", .type = CALLER_TYPE_CLONE};
    assert_string_equal(get_clone_network_name(&app), "ETHClone");
}

// =============================================================================
// Runner
// =============================================================================

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup(test_find_dynamic_empty_list_returns_null, reset_globals),
        cmocka_unit_test_setup(test_find_dynamic_one_match, reset_globals),
        cmocka_unit_test_setup(test_find_dynamic_walks_list_and_finds_second, reset_globals),
        cmocka_unit_test_setup(test_get_name_known_hardcoded_returns_name, reset_globals),
        cmocka_unit_test_setup(test_get_name_zero_chain_id_returns_null, reset_globals),
        cmocka_unit_test_setup(test_get_name_unknown_chain_id_returns_null, reset_globals),
        cmocka_unit_test_setup(test_get_name_dynamic_shadows_hardcoded, reset_globals),
        cmocka_unit_test_setup(test_get_as_string_known_copies_name, reset_globals),
        cmocka_unit_test_setup(test_get_as_string_unknown_formats_decimal, reset_globals),
        cmocka_unit_test_setup(test_get_as_string_unknown_small_buffer_fails, reset_globals),
        cmocka_unit_test_setup(test_chain_compatible_known_true, reset_globals),
        cmocka_unit_test_setup(test_chain_compatible_native_true, reset_globals),
        cmocka_unit_test_setup(test_chain_compatible_unknown_false, reset_globals),
        cmocka_unit_test_setup(test_app_compatible_same_chain_id, reset_globals),
        cmocka_unit_test_setup(test_app_compatible_both_in_table, reset_globals),
        cmocka_unit_test_setup(test_app_compatible_target_unknown_rejected, reset_globals),
        cmocka_unit_test_setup(test_get_tx_chain_id_legacy_reads_v, reset_globals),
        cmocka_unit_test_setup(test_get_tx_chain_id_eip1559_reads_tmpcontent, reset_globals),
        cmocka_unit_test_setup(test_get_tx_chain_id_eip2930_reads_tmpcontent, reset_globals),
        cmocka_unit_test_setup(test_get_tx_chain_id_eip7702_reads_tmpcontent, reset_globals),
        cmocka_unit_test_setup(test_get_tx_chain_id_unknown_type_returns_zero, reset_globals),
        cmocka_unit_test_setup(test_get_network_as_string_uses_current_tx_chain_id, reset_globals),
        cmocka_unit_test_setup(test_displayable_ticker_known_returns_table, reset_globals),
        cmocka_unit_test_setup(test_displayable_ticker_falls_back_to_chain_cfg, reset_globals),
        cmocka_unit_test_setup(test_displayable_ticker_unknown_returns_placeholder, reset_globals),
        cmocka_unit_test_setup(test_displayable_ticker_dynamic_shadows, reset_globals),
        cmocka_unit_test_setup(test_clone_name_null_app_returns_null, reset_globals),
        cmocka_unit_test_setup(test_clone_name_non_clone_returns_null, reset_globals),
        cmocka_unit_test_setup(test_clone_name_clone_returns_name, reset_globals),
    };
    return cmocka_run_group_tests(tests, NULL, NULL);
}
