/*
 * Copied from file generated by tools/gen_networks.py
 */

#ifndef NETWORK_ICONS_GENERATED_H_
#define NETWORK_ICONS_GENERATED_H_

#include <stdint.h>
#include "nbgl_types.h"

typedef struct {
    uint64_t chain_id;
    const nbgl_icon_details_t *icon;
} network_icon_t;

extern const network_icon_t g_network_icons[10];

#endif  // NETWORK_ICONS_GENERATED_H_
