name: ClusterFuzzLite cron tasks
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  schedule:
    - cron: '0 17 * * 6'  # At 05:00 PM, only on Saturday

permissions: read-all

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.mode }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: batch
            sanitizer: address
          - mode: batch
            sanitizer: memory
          - mode: prune
            sanitizer: address
          - mode: coverage
            sanitizer: coverage
    steps:
      - name: Build Fuzzers (${{ matrix.mode }} - ${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          language: c  # Change this to the language you are fuzzing.
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run Fuzzers (${{ matrix.mode }} - ${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: ${{ github.event_name == 'push' && 600 || 18000 }} # 10 min for push, else 5 hours
          mode: ${{ matrix.mode }}
          sanitizer: ${{ matrix.sanitizer }}
