---
name: Check SDK submodule version

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_check_SDK:
    name: Check Ethereum plugin SDK submodule is up-to-date
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_check_ethereum_sdk.yml@v1
