---
name: Python client checks, package build and deployment

on:
  workflow_dispatch:
  push:
    tags:
      - 'client-*'
    branches:
      - develop
      - master
    paths:
      - client/**
      - .github/workflows/python-client.yml
  pull_request:
    paths:
      - client/**
      - .github/workflows/python-client.yml

jobs:
  lint:
    name: Call Ledger Python linters
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_linter: flake8
      run_type_check: true
      src_directory: src
      setup_directory: client
      req_directory: client

  package_and_deploy:
    name: Build and deploy the Ethereum client Python package
    needs: [lint]
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_pypi_deployment.yml@v1
    with:
      package_name: ledger_app_clients.ethereum
      publish: ${{ startsWith(github.ref, 'refs/tags/') }}
      package_directory: ./client/
      jfrog_deployment: false
      release: false
    secrets:
      pypi_token: ${{ secrets.PYPI_PUBLIC_API_TOKEN }}
