---
name: Python client checks, package build and deployment

on:
  workflow_dispatch:
  push:
    tags:
      - 'client-*'
    branches:
      - develop
      - master
    paths:
      - client/**
      - .github/workflows/python-client.yml
  pull_request:
    paths:
      - client/**
      - .github/workflows/python-client.yml

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - run: pip install flake8 flake8-pyproject
      - name: Flake8 lint Python code
        run: (cd client && flake8 src/)

  mypy:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - run: pip install mypy
      - name: Mypy type checking
        run: (cd client && mypy src/)

  package_and_deploy:
    name: Build and deploy the Ethereum client Python package
    needs: [lint, mypy]
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_pypi_deployment.yml@v1
    with:
      package_name: ledger_app_clients.ethereum
      publish: ${{ startsWith(github.ref, 'refs/tags/') }}
      package_directory: ./client/
      jfrog_deployment: false
    secrets:
      pypi_token: ${{ secrets.PYPI_PUBLIC_API_TOKEN  }}
